### ISSUE TITLE
404 error code

### ISSUE THREAD

**Issue by f1r3walled** [luijait/DarkGPT#11]
Hi, Dear,
I still have the error informing 404 error code.
The thing is that I'm a monthly subscriber of ChatGPT (so I do have GPT4). Additionally, I have the API key with the proper permissions working and I also charged additional credits in my GPT account. My references are: https://platform.openai.com/account/billing/overview and https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

Finally, I'm paid subscriber at DeHashed, with valid credits and API properly configured.

Any idea to make it work?

![darkgpt](https://github.com/luijait/DarkGPT/assets/13592660/4f751187-3e46-41d0-8d05-dfc3af942870)

**Comment by f1r3walled** [comment]
My fault I messed with. Now it works, but it just brought a few results. If searching directly through the Dehashed console, I can thousands of results.

**Comment by luijait** [comment]
You can combine although modify the code to save retrieval's in txt
