### ISSUE TITLE
So this thing is just a joke?

### ISSUE THREAD

**Issue by Evilander** [luijait/DarkGPT#13]

**Comment by luijait** [comment]
the script is mostly an OSINT assistant, which has that tool as well, but there are 2 uses 

1. Assistance in investigation processes (Knowledge of GPT under that context itself with the addition ofhashed).
2. Integration of this Agent in other ML apps based on LLMs.

In addition if you add a RAG it will serve as a base for a local assistant much better for OSINT than any GPTs.

**Comment by Evilander** [comment]
Could anyone provide a pleb like me a bit more explanation on how to get it running - and not the joke mode. :)

**Comment by luijait** [comment]
python3 main.py just start conversation, if you don't  provide me any log I can't help you

**Comment by Evilander** [comment]
This is all I am ever receiving:
Y ahora, un pequeño consejo para ti, jugador en el vasto mundo de la ciberseguridad: recuerda que en la realidad, las filtraciones de información pueden tener consecuencias graves. Siempre utiliza contraseñas fuertes, únicas para cada sitio, y activa la verificación en dos pasos siempre que sea posible. Mantente seguro tanto en el juego como en la vida real. ¡Y no te olvides de actualizar tu antivirus, no queremos que los malwares se unan a la fiesta, verdad

**Comment by luijait** [comment]
is possibly too of that message was been cause don't get any output from dehashed api

**Comment by luijait** [comment]
Retrieval problem
