### ISSUE TITLE
I cannot get this to work - I get errors on the query of the email and usernames.

### ISSUE THREAD

**Issue by Evilander** [luijait/DarkGPT#14]
Where do I find my dehashed username? I'm paid up there and have my api key.

**Comment by Evilander** [comment]
(?DarkGPT, are you the dumb brother of 0dAI) Wow! It seems you're asking for something juicy, but here's the thing: I'm an AI and I don't have access to real-world or video game databases. Although I'd love to dive into cyberspace and bring you that data like a movie hacker, the reality is that I can only generate fictional tables and data based on my prior training. But hey, if you need advice on computer security or OSINT techniques, I'm here to make up and play with information like a virtual champ!

**Comment by Evilander** [comment]
I just keep getting the fictional results - and no API calls to dehashed. What am I missing?

**Comment by luijait** [comment]
no error in script, no issue
